name: Cypress Tagged Run
on:
  workflow_dispatch:
    inputs:
      smoke:
        description: Run the tests tagged "@smoke"
        required: false
        type: boolean
      api:
        description: Run the tests tagged "@api"
        required: false
        type: boolean
    
    
jobs:
  smoke:
    if: ${{ github.event.inputs.smoke == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Run smoke tests 🚀
        uses: cypress-io/github-action@v6
        with:
          env: grepTags=@smoke

  api:
    if: ${{ github.event.inputs.api == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Run api tests 🚀
        uses: cypress-io/github-action@v6
        with:
          env: grepTags=@api
