name: tagged
on:
  workflow_dispatch:
    inputs:
      smoke:
        description: Run the tests tagged "@smoke"
        required: false
        type: boolean
      regression:
        description: Run the tests tagged "@regression"
        required: false
        type: boolean
    
    
jobs:
  smoke:
    if: ${{ github.event.inputs.smoke == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      # https://github.com/cypress-io/github-action
      - name: Run smoke tests 🚀
        uses: cypress-io/github-action@v2
        with:
          env: grepTags=@smoke

  regression:
    if: ${{ github.event.inputs.regression == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4


      - name: Run regression tests 🚀
        uses: cypress-io/github-action@v2
        with:
          env: grepTags=@regression
