name: Tagged
on:
  workflow_dispatch:
    inputs:
      smoke:
        description: Run the tests tagged "@smoke"
        required: false
        type: boolean

jobs:
  tagged-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        if: ${{ github.event.inputs.smoke == 'true' }}      
        uses: cypress-io/github-action@v6
        with:
          env: grepTags=@smoke
